services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/Interdisciplinar-Med
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=proj_internato

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proj_internato
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./BANCO.sql:/docker-entrypoint-initdb.d/01-banco.sql
      - ./Procedure.sql:/docker-entrypoint-initdb.d/02-procedure.sql
      - ./view.sql:/docker-entrypoint-initdb.d/03-view.sql
      - ./function.sql:/docker-entrypoint-initdb.d/04-function.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: